# Generated by Django 4.2 on 2023-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttype',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='clienttype',
            table='client_type',
        ),
    ]
