# Generated by Django 4.2 on 2023-09-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multilevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilevel',
            name='parent',
        ),
        migrations.AddField(
            model_name='multilevel',
            name='direct_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='core.multilevel'),
        ),
        migrations.AddField(
            model_name='multilevel',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='multilevel',
            name='indirect_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='core.multilevel'),
        ),
        migrations.AddField(
            model_name='multilevel',
            name='password1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='multilevel',
            name='password2',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
