# Generated by Django 4.2 on 2023-07-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMKHOA',
            fields=[
                ('makhoa', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tenkhoa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DMMH',
            fields=[
                ('mamh', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tenmh', models.CharField(max_length=30)),
                ('sotiet', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DMSV',
            fields=[
                ('masv', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('hosv', models.CharField(max_length=30)),
                ('tensv', models.CharField(max_length=10)),
                ('phai', models.BooleanField(default=0)),
                ('ngaysinh', models.DateField()),
                ('noisinh', models.CharField(max_length=25)),
                ('hocbong', models.FloatField()),
                ('khoa', models.ForeignKey(db_column='makhoa', on_delete=django.db.models.deletion.CASCADE, to='QLDIEM.dmkhoa')),
            ],
        ),
        migrations.CreateModel(
            name='KETQUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanthi', models.SmallIntegerField()),
                ('diem', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mh', models.ForeignKey(db_column='mamh', on_delete=django.db.models.deletion.CASCADE, to='QLDIEM.dmmh')),
                ('sv', models.ForeignKey(db_column='masv', on_delete=django.db.models.deletion.CASCADE, to='QLDIEM.dmsv')),
            ],
        ),
    ]
